# Generated by Django 5.1 on 2024-08-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChildA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('relation_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inheritance.relationa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('relation_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inheritance.relationb')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
